Output output/jjui_details_restore.gif
#Output output/jjui_details_restore.webm

Require jjui
Require jj

Set Theme Dracula
Set Padding 0
Set FontSize 20
Set Width 1000
Set Height 600
Set Framerate 24
Set WindowBarSize 0

Hide
Type "./init.sh && jjui repo/" Enter
Wait /revisions/
Show

Sleep 1s
Type "l"
Sleep 2s
Type "hjjjjjljjj"
Sleep 1s
Type "r"
Sleep 1s
Enter
Sleep 1s
Type "kkkkkl"
Sleep 1s
Escape
Sleep 2s
Type "q"

